name: Aurora
title: Aurora | A recording blog for game development
description: A beautiful game world that you might interested in.
tags:
  - blog
  - roguelike
  - turnbased
  - unity
# make newest post in main region
show_hero: true
menu:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
